export interface Project {
  id: number
  slug: string
  title: string
  titleAr: string
  category: 'saas' | 'ecommerce' | 'web' | 'design' | 'ai'
  image: string
  images?: string[]
  url: string
  github?: string
  date: string
  tags: string[]
  featured?: boolean
  description?: string
  descriptionAr?: string
  longDescription?: string
  longDescriptionAr?: string
  role?: string
  roleAr?: string
  features?: string[]
  featuresAr?: string[]
  challenges?: string[]
  challengesAr?: string[]
  stack?: string[]
}

export const useProjects = () => {
  const projects: Project[] = [
    {
      id: 26,
      slug: 'zahnarztpraxis-farahani',
      title: 'Zahnarztpraxis Farahani',
      titleAr: 'عيادة أسنان فراهاني',
      category: 'web',
      image: '/images/projects/zahnarztfarahani.png',
      url: 'https://zahnarztfarahani.de/',
      date: '2026-09',
      tags: ['Next.js', 'Laravel', 'Filament', 'SEO', 'Germany'],
      featured: false,
      description: 'Full-stack website, custom CMS and online booking for a dental practice in Karlsruhe, Germany. Delivered at AstraMind, including hosting and technical SEO.',
      descriptionAr: 'موقع متكامل مع نظام إدارة محتوى مخصص وحجز مواعيد عبر الإنترنت لعيادة أسنان في كارلسروه بألمانيا. تم تنفيذه ضمن AstraMind مع الاستضافة وتحسين SEO التقني.',
      longDescription: 'A complete digital presence for Zahnarztpraxis Maryam Farahani, a dental practice in Karlsruhe-Weststadt, built and hosted end to end at AstraMind. The public site is a Next.js frontend deployed on Netlify; it is powered by a custom multi-tenant Laravel 12 + Filament CMS hosted on Strato. The practice team manages every page through a visual page builder with 16 block types, live device preview and a built-in SEO checklist. Patients can book appointments online, read the treatment catalogue, and see holiday closures together with the covering dentists. The site is GDPR-compliant: a categorised consent banner with server-side proof of consent, OpenStreetMap embeds that only load after consent, and Cloudflare Turnstile on the contact form. Technical SEO for German local search covers canonical URLs, a sitemap, structured data and Core Web Vitals.',
      longDescriptionAr: 'حضور رقمي متكامل لعيادة أسنان مريم فراهاني في كارلسروه-فيستشتات، تم بناؤه واستضافته بالكامل ضمن AstraMind. الواجهة العامة مبنية بـ Next.js ومنشورة على Netlify، وتعمل بنظام إدارة محتوى مخصص متعدد المستأجرين مبني بـ Laravel 12 وFilament ومستضاف على Strato. يدير فريق العيادة كل صفحة عبر منشئ صفحات مرئي يضم 16 نوعًا من الكتل مع معاينة حية للأجهزة وقائمة تحقق SEO مدمجة. يمكن للمرضى حجز المواعيد عبر الإنترنت وتصفح كتالوج العلاجات ومعرفة فترات الإغلاق والأطباء البدلاء. الموقع متوافق مع اللائحة العامة لحماية البيانات (GDPR) عبر شريط موافقة مصنّف مع توثيق الموافقة على الخادم، وخرائط OpenStreetMap لا تُحمَّل إلا بعد الموافقة، وحماية Cloudflare Turnstile لنموذج الاتصال، إضافة إلى تحسين SEO التقني للبحث المحلي الألماني.',
      role: 'Full Stack Developer, Hosting & SEO (AstraMind)',
      roleAr: 'مطوّر متكامل واستضافة وSEO (AstraMind)',
      features: [
        'Visual page builder with 16 block types, live desktop/tablet/mobile preview and SEO scoring',
        'Online appointment booking with availability per doctor and service, plus email reminders',
        'Holiday closures with automatic cover-practice notices on the home page',
        'GDPR consent management with server-side proof of consent and consent-gated maps',
        'Role-based admin (Super-Admin, Admin, Staff) with two-factor authentication',
        'German and English admin panel and patient emails',
        'Technical SEO: canonical URLs, sitemap, structured data and Core Web Vitals tuning',
      ],
      featuresAr: [
        'منشئ صفحات مرئي يضم 16 نوعًا من الكتل مع معاينة حية للحاسوب والجهاز اللوحي والجوال وتقييم SEO',
        'حجز مواعيد عبر الإنترنت حسب توفر كل طبيب وخدمة مع رسائل تذكير بالبريد الإلكتروني',
        'إدارة فترات الإجازة مع إعلان تلقائي عن العيادات البديلة في الصفحة الرئيسية',
        'إدارة موافقات GDPR مع توثيق الموافقة على الخادم وخرائط لا تُحمَّل إلا بعد الموافقة',
        'لوحة إدارة بصلاحيات متعددة (مدير عام، مدير، موظف) مع مصادقة ثنائية',
        'لوحة إدارة ورسائل بريد للمرضى باللغتين الألمانية والإنجليزية',
        'تحسين SEO التقني: عناوين URL أساسية وخريطة موقع وبيانات منظمة وتحسين مؤشرات الويب الأساسية',
      ],
      challenges: [
        'Designing a block-based page builder flexible enough for non-technical practice staff while keeping the public pages fast and SEO-friendly',
        'Meeting German GDPR requirements without degrading the visitor experience, including provable consent and no third-party loads before consent',
        'Splitting hosting between Netlify (Next.js frontend) and Strato (Laravel API and MySQL) while keeping canonical URLs, sitemap and previews consistent',
      ],
      challengesAr: [
        'تصميم منشئ صفحات قائم على الكتل يناسب طاقم العيادة غير التقني مع الحفاظ على سرعة الصفحات العامة وملاءمتها لمحركات البحث',
        'تلبية متطلبات GDPR الألمانية دون الإضرار بتجربة الزائر، بما في ذلك توثيق الموافقة وعدم تحميل أي محتوى خارجي قبلها',
        'توزيع الاستضافة بين Netlify (واجهة Next.js) وStrato (واجهة Laravel البرمجية وقاعدة MySQL) مع الحفاظ على اتساق عناوين URL الأساسية وخريطة الموقع والمعاينات',
      ],
      stack: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Laravel 12', 'Filament', 'MySQL', 'Netlify', 'Strato'],
    },
    {
      id: 25,
      slug: 'rsk-platform',
      title: 'RSK Platform',
      titleAr: 'منصة RSK',
      category: 'web',
      image: '/images/projects/rsk-platform.com.png',
      url: 'https://rsk-platform.com/#services',
      date: '2026-06',
      tags: ['Nuxt 3', 'Express', 'Tailwind CSS', 'PostgreSQL'],
      featured: true,
      description: 'A comprehensive digital agency platform offering full-scale web/app development, social media management, interactive cost calculators, and robust VPS infrastructure.',
      descriptionAr: 'منصة رقمية متكاملة تقدم خدمات تطوير المواقع والتطبيقات، وإدارة وسائل التواصل الاجتماعي، وحاسبة تفاعلية لتكلفة المشاريع، مع بنية تحتية قوية لخوادم VPS.',
      longDescription: 'RSK Platform is a state-of-the-art digital services agency website built using a highly performant Nuxt 3 frontend with Tailwind CSS and an Express backend. It features an interactive, multi-step project cost calculator, service request forms, dynamic localized content, and dockerized deployment on a secure VPS environment. The project showcases how marketing, software engineering, and infrastructure can seamlessly merge to accelerate business growth.',
      longDescriptionAr: 'منصة RSK هي موقع ويب متطور لوكالة خدمات رقمية، تم بناؤه باستخدام واجهة أمامية عالية الأداء بـ Nuxt 3 مع Tailwind CSS وخلفية Express. يتميز الموقع بحاسبة تفاعلية متعددة الخطوات لتقدير تكاليف المشاريع البرمجية والتسويقية، ونماذج طلب الخدمات، ومحتوى محلي ديناميكي، مع نشر حاويات Docker على بيئة VPS آمنة. يوضح المشروع كيف يمكن للتسويق والهندسة البرمجية والبنية التحتية أن تتكامل بسلاسة لتسريع نمو الأعمال.',
      role: 'Lead Full Stack Developer & System Architect',
      roleAr: 'مطوّر متكامل رئيسي ومهندس نظم',
      features: [
        'Interactive multi-step project cost and architecture calculator',
        'High-performance Nuxt 3 with Server-Side Rendering (SSR)',
        'Dynamic service request system and CRM lead capture',
        'Full multilingual support with RTL Arabic layout',
        'Dockerized deployment workflow on a secure VPS with Nginx and PostgreSQL',
      ],
      featuresAr: [
        'حاسبة تفاعلية متعددة الخطوات لتقدير التكلفة واقتراح البنية البرمجية',
        'واجهة Nuxt 3 فائقة الأداء مع عرض جانب الخادم (SSR)',
        'نظام ديناميكي لطلب الخدمات وتجميع بيانات العملاء المحتملين',
        'دعم كامل للتعدد اللغوي مع تخطيط اتجاه اليمين إلى اليسار (RTL) للعربية',
        'سير عمل نشر معزز بحاويات Docker على خادم VPS آمن مع Nginx وPostgreSQL',
      ],
      challenges: [
        'Implementing a complex, interactive budgeting algorithm on the client side that perfectly recommends matching database and server architectures based on user needs',
        'Optimizing initial load and core web vitals for a rich marketing experience containing large graphics and interactive SVGs',
        'Securing the contact and application endpoints against automated spam while maintaining an elegant, hassle-free user experience',
      ],
      challengesAr: [
        'تنفيذ خوارزمية ميزانية تفاعلية معقدة من جانب العميل توصي بدقة بقاعدة البيانات وبنية الخادم المقترحة بناءً على احتياجات المستخدم',
        'تحسين التحميل الأولي ومؤشرات الويب الأساسية لتجربة تسويقية غنية تحتوي على رسومات كبيرة وعناصر SVG تفاعلية',
        'تأمين نقاط اتصال وطلب الخدمات ضد البريد العشوائي التلقائي مع الحفاظ على تجربة مستخدم أنيقة وسلسة',
      ],
      stack: ['Nuxt 3', 'Vue 3', 'TypeScript', 'Tailwind CSS', 'Node.js', 'Express', 'PostgreSQL', 'Docker'],
    },
    {
      id: 24,
      slug: 'az-containers-belgium',
      title: 'AZ Containers Belgium',
      titleAr: 'AZ كونتينرز بلجيكا',
      category: 'web',
      image: '/images/projects/azcontainers.png',
      url: 'https://azcontainers.be',
      date: '2026-04',
      tags: ['Nuxt 3', 'SEO', 'Belgium', 'Multi-language'],
      featured: false,
      description: 'Complete website relooking and SEO overhaul for AZ Containers Belgium — a Belgian container rental company serving Brussels and surrounding areas.',
      descriptionAr: 'إعادة تصميم كاملة وتحسين شامل لمحركات البحث لموقع AZ Containers Belgium — شركة تأجير حاويات بلجيكية تخدم بروكسل والمناطق المحيطة بها.',
      longDescription: 'A full website redesign and SEO overhaul for AZ Containers Belgium, a container rental service operating in Brussels and surrounding Belgian regions. The project involved building a modern, performant Nuxt 3 front-end with tri-lingual support (French, English, Dutch), a custom Laravel + Filament admin backend, and a comprehensive SEO strategy. Key deliverables include a video hero section, interactive container catalog with 8–30 m³ sizing options, Google Maps delivery-zone integration, a Cloudflare Turnstile-protected contact and order form, dark mode support, and a sitemap/robots.txt setup fully optimised for Belgian local search.',
      longDescriptionAr: 'إعادة تصميم كاملة وتحسين شامل لـ SEO لموقع AZ Containers Belgium، خدمة تأجير حاويات تعمل في بروكسل والمناطق البلجيكية المحيطة بها. تضمّن المشروع بناء واجهة أمامية حديثة وعالية الأداء بـ Nuxt 3 مع دعم ثلاثي اللغات (فرنسي، إنجليزي، هولندي)، ولوحة خلفية مخصصة بـ Laravel وFilament، واستراتيجية SEO شاملة. تشمل المخرجات الرئيسية قسمًا رئيسيًا (Hero) بخلفية فيديو، وكتالوج حاويات تفاعلي، وتضمين خريطة Google Maps لمنطقة التوصيل، ونموذج طلب محمي بـ Cloudflare Turnstile، ودعم الوضع الداكن، وإعداد خريطة الموقع وملف robots.txt محسّن للبحث المحلي البلجيكي.',
      role: 'Lead Full Stack Developer & SEO Specialist',
      roleAr: 'مطوّر متكامل رئيسي ومتخصص SEO',
      features: [
        'Complete UI/UX relooking with dark mode support',
        'Tri-lingual site (FR / EN / NL) with hreflang and prefix routing',
        'On-page SEO: canonical URLs, OG tags, structured data, sitemap.xml',
        'Google Analytics 4 integration via GTM (G-QD4C7YVMT5)',
        'Cloudflare Turnstile CAPTCHA on contact and order forms',
        'Laravel + Filament admin panel for content and order management',
        'Lazy-loaded Google Maps delivery-zone embed',
        'Brotli/Gzip asset compression with immutable cache headers',
      ],
      featuresAr: [
        'إعادة تصميم كاملة لواجهة المستخدم مع دعم الوضع الداكن',
        'موقع ثلاثي اللغات (FR / EN / NL) مع hreflang وتوجيه البادئة',
        'تحسين SEO في الصفحة: عناوين URL الأساسية وعلامات OG والبيانات المنظمة وخريطة الموقع',
        'تكامل Google Analytics 4 عبر GTM',
        'Cloudflare Turnstile CAPTCHA في نماذج الاتصال والطلب',
        'لوحة إدارة Laravel + Filament لإدارة المحتوى والطلبات',
        'تضمين خريطة Google Maps لمنطقة التوصيل بالتحميل الكسول',
        'ضغط الملفات بـ Brotli/Gzip مع ترويسات تخزين مؤقت ثابتة (immutable)',
      ],
      challenges: [
        'Designing a scalable tri-lingual routing strategy with SEO-friendly URL prefixes per locale while preserving static export compatibility',
        'Integrating a headless Laravel + Filament backend for order management without coupling it to the Nuxt SSG build pipeline',
        'Achieving strong Core Web Vitals scores despite a full-screen background video and lazy-loaded third-party embeds (Google Maps, GTM)',
      ],
      challengesAr: [
        'تصميم استراتيجية توجيه ثلاثية اللغات قابلة للتوسع مع بادئات URL صديقة لمحركات البحث لكل لغة مع الحفاظ على التوافق مع التصدير الثابت',
        'دمج خلفية Laravel وFilament منفصلة (Headless) لإدارة الطلبات دون ربطها بمسار بناء Nuxt SSG',
        'تحقيق درجات Core Web Vitals قوية على الرغم من فيديو الخلفية بملء الشاشة والتضمينات المحملة كسلًا من طرف ثالث',
      ],
      stack: ['Nuxt 3', 'Vue 3', 'TypeScript', 'Tailwind CSS', 'Laravel', 'Filament', 'MySQL', '@nuxtjs/i18n'],
    },
    {
      id: 1,
      slug: 'fastcaisse-ordering-platform',
      title: 'FastCaisse Ordering Platform',
      titleAr: 'منصة طلب FastCaisse',
      category: 'saas',
      image: '/images/projects/ordering-platform.jpg',
      url: 'https://stores-fastcaisse.be/en',
      date: '2026-01',
      tags: ['Vue 3', 'Laravel', 'SaaS', 'Multi-language'],
      featured: true,
      description: 'Multi-restaurant online ordering SaaS with kiosk mode, payment integration, and multi-language support.',
      descriptionAr: 'منصة طلب طعام SaaS متعددة المطاعم مع وضع الكشك ودمج الدفع ودعم متعدد اللغات.',
      longDescription: 'A comprehensive multi-restaurant online ordering SaaS platform built from the ground up. The system supports restaurant onboarding, menu management, real-time order tracking, kiosk mode for in-store self-service, and seamless payment integration with Stripe and Mollie. It features multi-language support (EN, FR, NL, AR), responsive design, and an admin dashboard for restaurant owners.',
      longDescriptionAr: 'منصة SaaS شاملة متعددة المطاعم للطلب عبر الإنترنت، مبنية من الصفر. يدعم النظام تسجيل المطاعم وإدارة القوائم وتتبع الطلبات في الوقت الفعلي ووضع الكشك للخدمة الذاتية ودمج الدفع مع Stripe وMollie.',
      role: 'Lead Full Stack Developer',
      roleAr: 'مطوّر متكامل رئيسي',
      features: ['Multi-tenant restaurant onboarding', 'Real-time order tracking with WebSocket', 'Kiosk mode for in-store self-service', 'Stripe and Mollie payment integration', 'Multi-language support (EN, FR, NL, AR) with RTL', 'Admin dashboard with analytics'],
      featuresAr: ['تسجيل المطاعم وإدارتها ضمن بنية متعددة المستأجرين', 'تتبع الطلبات في الوقت الفعلي مع WebSocket', 'وضع الكشك للخدمة الذاتية', 'دمج بوابات دفع Stripe وMollie', 'دعم متعدد اللغات مع RTL', 'لوحة إدارة مع تحليلات'],
      challenges: ['Designing a scalable multi-tenant architecture supporting isolated restaurant data', 'Implementing real-time order synchronization between customer, kitchen, and admin views', 'Building a seamless payment flow supporting multiple European payment providers'],
      challengesAr: ['تصميم بنية متعددة المستأجرين قابلة للتوسع لعزل بيانات كل مطعم', 'تنفيذ مزامنة الطلبات في الوقت الفعلي بين واجهات العميل والمطبخ والإدارة', 'بناء تدفق دفع سلس يدعم مزودي دفع أوروبيين متعددين'],
      stack: ['Nuxt 3', 'Vue 3', 'TypeScript', 'Laravel 10', 'MySQL', 'Redis', 'Tailwind CSS', 'Stripe', 'Mollie'],
    },
    {
      id: 2,
      slug: 'fastcaisse-kiosk',
      title: 'FastCaisse Kiosk',
      titleAr: 'كشك FastCaisse',
      category: 'saas',
      image: '/images/projects/kiosk.png',
      url: 'https://kiosk.fastfoodelivery.be/',
      date: '2025-12',
      tags: ['Vue 3', 'Kiosk', 'Touch UI'],
      featured: true,
      description: 'Self-service kiosk application for in-restaurant ordering with touch-optimized UI.',
      descriptionAr: 'تطبيق كشك الخدمة الذاتية للطلب داخل المطعم مع واجهة مستخدم محسّنة للمس.',
      longDescription: 'A dedicated self-service kiosk application designed for restaurant environments. Built with Next.js 15 and optimized for large touch screens, providing an intuitive ordering experience with category browsing, item customization, cart management, and integrated payment processing.',
      longDescriptionAr: 'تطبيق كشك خدمة ذاتية مخصص مصمم لبيئات المطاعم. مبني بـ Next.js 15 ومحسّن لشاشات اللمس الكبيرة، يوفر تجربة طلب بديهية مع تصفح الفئات وتخصيص العناصر وإدارة السلة.',
      role: 'Lead Frontend Developer',
      roleAr: 'مطوّر واجهة أمامية رئيسي',
      features: ['Touch-optimized interface for large kiosk displays', 'Category browsing with visual menu cards', 'Item customization with modifiers and extras', 'Integrated payment terminal support', 'Auto-reset idle state for next customer', 'Multi-language menu display'],
      featuresAr: ['واجهة محسّنة للمس لشاشات الكشك الكبيرة', 'تصفح الفئات مع بطاقات قائمة مرئية', 'تخصيص العناصر مع الإضافات', 'دعم محطة الدفع المتكاملة', 'إعادة تعيين تلقائية عند الخمول', 'عرض قائمة متعدد اللغات'],
      stack: ['Next.js 15', 'React', 'TypeScript', 'Tailwind CSS'],
    },
    {
      id: 3,
      slug: 'lindenberg-apotheke',
      title: 'Lindenberg Apotheke',
      titleAr: 'صيدلية ليندنبرغ',
      category: 'web',
      image: '/images/projects/Lindenberg-Apotheke.png',
      url: 'https://lindenberg-apotheke.de/',
      date: '2025-11',
      tags: ['Laravel', 'SEO', 'Germany'],
      description: 'Modern pharmacy website for a German pharmacy with online services and SEO optimization.',
      descriptionAr: 'موقع حديث لصيدلية ألمانية مع خدمات عبر الإنترنت وتحسين لمحركات البحث.',
      longDescription: 'A modern, SEO-optimized website for Lindenberg Apotheke in Germany. The site features online pharmacy services, product catalog, health articles, and appointment booking. Built with a focus on Core Web Vitals, accessibility, and local SEO to drive foot traffic and online engagement.',
      longDescriptionAr: 'موقع ويب حديث محسّن لمحركات البحث لصيدلية ليندنبرغ في ألمانيا. يتميز الموقع بخدمات الصيدلية عبر الإنترنت وكتالوج المنتجات ومقالات صحية وحجز المواعيد.',
      role: 'Full Stack Developer',
      roleAr: 'مطوّر متكامل',
      features: ['SEO-optimized for local German search', 'Online pharmacy services integration', 'Health articles and blog section', 'Mobile-first responsive design', 'Core Web Vitals optimized'],
      featuresAr: ['محسّن للبحث المحلي في ألمانيا', 'دمج خدمات الصيدلية عبر الإنترنت', 'قسم مقالات صحية ومدونة', 'تصميم متجاوب للجوال أولًا', 'محسّن لمؤشرات الويب الأساسية'],
      stack: ['Laravel', 'Tailwind CSS', 'MySQL', 'JavaScript'],
    },
    {
      id: 4,
      slug: 'astramind',
      title: 'Astramind',
      titleAr: 'أسترامايند',
      category: 'web',
      image: '/images/projects/Astramind.png',
      url: 'https://astramind.de/',
      date: '2025-09',
      tags: ['React', 'SEO', 'Germany'],
      description: 'Corporate website for a German tech company with modern design and SEO optimization.',
      descriptionAr: 'موقع شركة تقنية ألمانية بتصميم حديث وتحسين لمحركات البحث.',
      longDescription: 'A sleek corporate website built for AstraMind, a German technology company. Developed using Nuxt 3 and TypeScript with a focus on performance, accessibility, and search engine visibility. Achieved a 40% improvement in Lighthouse scores through technical optimization.',
      longDescriptionAr: 'موقع مؤسسي أنيق مبني لشركة AstraMind التقنية الألمانية. تم تطويره باستخدام Nuxt 3 وTypeScript مع التركيز على الأداء وإمكانية الوصول والظهور في محركات البحث.',
      role: 'Lead Web Developer & Project Manager',
      roleAr: 'مطوّر ويب رئيسي ومدير مشروع',
      features: ['40% improvement in Lighthouse scores', 'Nuxt 3 with server-side rendering', 'Fully responsive and accessible design', 'German-language SEO optimization'],
      featuresAr: ['تحسين بنسبة 40% في درجات Lighthouse', 'Nuxt 3 مع عرض جانب الخادم', 'تصميم متجاوب وقابل للوصول بالكامل', 'تحسين SEO باللغة الألمانية'],
      stack: ['Nuxt 3', 'TypeScript', 'Tailwind CSS', 'Vue 3'],
    },
    {
      id: 5,
      slug: 'emtethal-landing-page',
      title: 'Emtethal Landing Page',
      titleAr: 'صفحة هبوط امتثال',
      category: 'web',
      image: '/images/projects/EmtethalLandpage.png',
      url: 'https://emtethal.com/',
      date: '2025-09',
      tags: ['Laravel', 'Arabic', 'Landing Page'],
      description: 'Bilingual Arabic/English landing page with RTL support and modern design.',
      descriptionAr: 'صفحة هبوط ثنائية اللغة عربي/إنجليزي مع دعم RTL وتصميم حديث.',
      longDescription: 'A high-converting bilingual landing page built for Emtethal with full Arabic RTL support. Features smooth animations, responsive design, and optimized conversion funnels. The site serves both Arabic and English audiences with culturally appropriate design choices.',
      longDescriptionAr: 'صفحة هبوط ثنائية اللغة عالية التحويل مبنية لشركة امتثال مع دعم كامل للعربية (RTL). تتميز برسوم متحركة سلسة وتصميم متجاوب ومسارات تحويل محسّنة.',
      role: 'Full Stack Developer',
      roleAr: 'مطوّر متكامل',
      features: ['Full Arabic RTL layout support', 'Bilingual content management', 'Smooth scroll animations', 'Optimized conversion funnels', 'Mobile-first responsive design'],
      featuresAr: ['دعم كامل لتخطيط RTL العربي', 'إدارة محتوى ثنائية اللغة', 'رسوم متحركة سلسة عند التمرير', 'مسارات تحويل محسّنة', 'تصميم متجاوب للجوال أولًا'],
      stack: ['Laravel', 'Tailwind CSS', 'JavaScript', 'MySQL'],
    },
    {
      id: 6,
      slug: 'fastcaisse-marketing-site',
      title: 'FastCaisse Marketing Site',
      titleAr: 'موقع FastCaisse التسويقي',
      category: 'saas',
      image: '/images/projects/FastCaisse-langing.png',
      url: 'https://fastcaisse.be/',
      date: '2025-06',
      tags: ['Nuxt', 'SEO', 'Marketing'],
      featured: true,
      description: 'Marketing and landing site for FastCaisse SaaS platform with SEO-driven content strategy.',
      descriptionAr: 'موقع تسويقي وصفحة هبوط لمنصة FastCaisse SaaS مع استراتيجية محتوى مدفوعة بـ SEO.',
      longDescription: 'The marketing website for FastCaisse, designed to drive signups and organic traffic. Built with Nuxt 3 for optimal SEO performance, the site features a compelling product showcase, pricing pages, customer testimonials, and a blog. Achieved 75% organic traffic increase through technical SEO implementation.',
      longDescriptionAr: 'الموقع التسويقي لـ FastCaisse، مصمم لزيادة التسجيلات والزيارات العضوية. مبني بـ Nuxt 3 للأداء الأمثل في محركات البحث.',
      role: 'Full Stack Developer & SEO Specialist',
      roleAr: 'مطوّر متكامل ومتخصص SEO',
      features: ['75% organic traffic increase', 'SEO-optimized with structured data', 'Compelling product showcase', 'Blog with technical content', 'Multi-language support'],
      featuresAr: ['زيادة 75% في الزيارات العضوية', 'محسّن لمحركات البحث مع بيانات منظمة', 'عرض منتج مقنع', 'مدونة بمحتوى تقني', 'دعم متعدد اللغات'],
      stack: ['Nuxt 3', 'Vue 3', 'TypeScript', 'Tailwind CSS'],
    },
    {
      id: 7,
      slug: 'little-lemon-booking',
      title: 'Little Lemon Booking – Figma',
      titleAr: 'حجز ليتل ليمون',
      category: 'design',
      image: '/images/projects/littlelemonbookTable.png',
      url: 'https://www.figma.com/design/MXOErAiiJyuwJGhO9HCHuM/',
      date: '2024-10',
      tags: ['Figma', 'UX/UI', 'Coursera'],
      description: 'UX/UI design project for a restaurant booking system, completed as part of Meta certification.',
      descriptionAr: 'مشروع تصميم UX/UI لنظام حجز مطعم، تم إنجازه ضمن شهادة Meta المهنية.',
      longDescription: 'A comprehensive UX/UI design case study for a restaurant table booking application. Created as part of the Meta Front-End Developer Professional Certificate on Coursera. Includes user research, wireframing, high-fidelity prototypes, and usability testing documentation.',
      longDescriptionAr: 'دراسة حالة شاملة لتصميم UX/UI لتطبيق حجز طاولات المطعم. تم إنشاؤها ضمن شهادة Meta المهنية لمطوّري الواجهة الأمامية على Coursera.',
      role: 'UX/UI Designer',
      roleAr: 'مصمم UX/UI',
      features: ['User research and persona development', 'Wireframing and information architecture', 'High-fidelity interactive prototypes', 'Usability testing and iterations', 'Design system with reusable components'],
      featuresAr: ['أبحاث المستخدمين وبناء الشخصيات (Personas)', 'التخطيط الشبكي وهندسة المعلومات', 'نماذج أولية تفاعلية عالية الدقة', 'اختبار قابلية الاستخدام وتحسينات متكررة', 'نظام تصميم مع مكونات قابلة لإعادة الاستخدام'],
      stack: ['Figma', 'UX Research', 'Prototyping'],
    },
    {
      id: 8,
      slug: 'il-moro-group',
      title: 'IL Moro Group',
      titleAr: 'مجموعة إيل مورو',
      category: 'web',
      image: '/images/projects/www.ilmorogroup.be.png',
      url: 'https://www.ilmorogroup.be/',
      date: '2024-09',
      tags: ['Laravel', 'Belgium', 'Restaurant'],
      description: 'Restaurant group website for IL Moro in Belgium with online presence management.',
      descriptionAr: 'موقع مجموعة مطاعم إيل مورو في بلجيكا مع إدارة الحضور الرقمي.',
      longDescription: 'A professional website for IL Moro Group, a restaurant group based in Belgium. The site showcases multiple restaurant brands under one umbrella, featuring menu displays, location information, reservation capabilities, and event management.',
      longDescriptionAr: 'موقع ويب احترافي لمجموعة إيل مورو، مجموعة مطاعم مقرها بلجيكا. يعرض الموقع علامات تجارية متعددة للمطاعم تحت مظلة واحدة.',
      role: 'Full Stack Developer',
      roleAr: 'مطوّر متكامل',
      features: ['Multi-brand restaurant showcase', 'Online menu management', 'Reservation system', 'Responsive design'],
      featuresAr: ['عرض مطاعم متعددة العلامات التجارية', 'إدارة القوائم عبر الإنترنت', 'نظام حجز', 'تصميم متجاوب'],
      stack: ['Laravel', 'PHP', 'MySQL', 'Tailwind CSS', 'JavaScript'],
    },
    {
      id: 9,
      slug: 'fastcaisse-online-ordering',
      title: 'FastCaisse Online Ordering',
      titleAr: 'طلب FastCaisse الإلكتروني',
      category: 'saas',
      image: '/images/projects/fastcaisse_Food_PortalOrdering.png',
      url: 'https://fastcaisse.be/food/public/start',
      date: '2024-06',
      tags: ['Laravel', 'Vue', 'Food Delivery'],
      description: 'Food delivery ordering portal integrated with the FastCaisse POS ecosystem.',
      descriptionAr: 'بوابة لطلب توصيل الطعام متكاملة مع نظام FastCaisse POS.',
      longDescription: 'The original online ordering portal for the FastCaisse ecosystem, enabling customers to browse menus, customize orders, and arrange delivery or pickup. Integrated directly with the FastCaisse POS system for seamless order flow from customer to kitchen.',
      longDescriptionAr: 'بوابة الطلب الأصلية عبر الإنترنت ضمن منظومة FastCaisse، تمكّن العملاء من تصفح القوائم وتخصيص الطلبات واختيار التوصيل أو الاستلام.',
      role: 'Full Stack Developer',
      roleAr: 'مطوّر متكامل',
      features: ['Menu browsing with categories and search', 'Order customization and modifiers', 'Delivery and pickup options', 'Direct POS integration', 'Real-time order status updates'],
      featuresAr: ['تصفح القائمة مع الفئات والبحث', 'تخصيص الطلبات والإضافات', 'خيارات التوصيل والاستلام', 'تكامل مباشر مع نظام POS', 'تحديثات حالة الطلب في الوقت الفعلي'],
      stack: ['Laravel', 'Vue.js', 'MySQL', 'PHP', 'JavaScript'],
    },
    {
      id: 10,
      slug: 'gelato-naturale',
      title: 'Gelato Naturale',
      titleAr: 'جيلاتو ناتورالي',
      category: 'web',
      image: '/images/projects/gelatonaturale.jpg',
      url: 'https://gelatonaturale.be/gelatonaturale/',
      date: '2024-03',
      tags: ['Laravel', 'Belgium', 'Ice Cream'],
      description: 'Website for an artisan gelato shop in Belgium with product showcase.',
      descriptionAr: 'موقع ويب لمتجر جيلاتو حرفي في بلجيكا مع عرض المنتجات.',
      longDescription: 'A visually appealing website for Gelato Naturale, an artisan ice cream shop in Belgium. Features a product showcase with flavor descriptions, store locations, and brand storytelling.',
      longDescriptionAr: 'موقع ويب جذاب بصريًا لجيلاتو ناتورالي، متجر آيس كريم حرفي في بلجيكا. يتميز بعرض المنتجات مع أوصاف النكهات ومواقع المتاجر.',
      role: 'Full Stack Developer',
      roleAr: 'مطوّر متكامل',
      stack: ['Laravel', 'PHP', 'MySQL', 'CSS3'],
    },
    {
      id: 11,
      slug: 'seetaha-award-debugger',
      title: 'Seetaha Award Debugger',
      titleAr: 'مُصحح سيتاها',
      category: 'web',
      image: '/images/projects/seetahaward.jpg',
      url: '#',
      date: '2024-01',
      tags: ['PHP', 'Debug', 'WordPress'],
      description: 'Debugging and optimization tool for the Seetaha Award WordPress platform.',
      descriptionAr: 'أداة تصحيح وتحسين لمنصة جائزة سيتاها المبنية على WordPress.',
      role: 'WordPress Developer',
      roleAr: 'مطوّر WordPress',
      stack: ['PHP', 'WordPress', 'MySQL', 'JavaScript'],
    },
    {
      id: 12,
      slug: 'seetah-scc',
      title: 'Seetah SCC',
      titleAr: 'سيتاه SCC',
      category: 'web',
      image: '/images/projects/seetahscc.jpg',
      url: 'https://seetahscc.org/ar/',
      date: '2024-01',
      tags: ['Arabic', 'RTL', 'WordPress'],
      description: 'Arabic-first WordPress website with full RTL support for Seetah SCC organization.',
      descriptionAr: 'موقع WordPress بالعربية أولًا مع دعم كامل لـ RTL لمنظمة سيتاه SCC.',
      longDescription: 'An Arabic-first WordPress website developed for Seetah SCC organization. Features full RTL layout support, bilingual content management, and custom theme development tailored to the organization\'s needs.',
      longDescriptionAr: 'موقع WordPress بالعربية أولًا تم تطويره لمنظمة سيتاه SCC. يتميز بدعم كامل لتخطيط RTL وإدارة محتوى ثنائية اللغة.',
      role: 'WordPress Developer',
      roleAr: 'مطوّر WordPress',
      stack: ['WordPress', 'PHP', 'CSS3', 'JavaScript'],
    },
    {
      id: 13,
      slug: 'matthias-and-sea',
      title: 'Matthias and Sea – Seafood',
      titleAr: 'ماتياس والبحر',
      category: 'web',
      image: '/images/projects/matthiasandsea.png',
      url: 'https://www.matthiasandsea.be/matthias-and-sea/',
      date: '2023-12',
      tags: ['PHP', 'Restaurant', 'Belgium'],
      description: 'Seafood restaurant website in Belgium with menu showcase and online presence.',
      descriptionAr: 'موقع مطعم مأكولات بحرية في بلجيكا مع عرض القائمة والحضور الرقمي.',
      longDescription: 'A clean, appetizing website for Matthias and Sea, a seafood restaurant in Belgium. The site highlights the restaurant\'s fresh seafood offerings, daily specials, and dining atmosphere through high-quality imagery and intuitive navigation.',
      longDescriptionAr: 'موقع ويب أنيق وجذاب لمطعم ماتياس والبحر، مطعم مأكولات بحرية في بلجيكا.',
      role: 'Web Developer',
      roleAr: 'مطوّر ويب',
      stack: ['PHP', 'HTML5', 'CSS3', 'JavaScript'],
    },
    {
      id: 14,
      slug: 'geco-consulting',
      title: 'Geco Consulting',
      titleAr: 'جيكو للاستشارات',
      category: 'web',
      image: '/images/projects/gecocar.jpg',
      url: 'https://gecoconsulting.be',
      date: '2023-11',
      tags: ['Laravel', 'Belgium', 'Consulting'],
      description: 'Consulting firm website with service showcase and client management features.',
      descriptionAr: 'موقع شركة استشارات مع عرض الخدمات وميزات إدارة العملاء.',
      longDescription: 'A professional website for Geco Consulting, a Belgian consulting firm. Features a comprehensive service catalog, team profiles, case studies, and contact management.',
      longDescriptionAr: 'موقع ويب احترافي لشركة جيكو للاستشارات، شركة استشارات بلجيكية.',
      role: 'Full Stack Developer',
      roleAr: 'مطوّر متكامل',
      stack: ['Laravel', 'PHP', 'MySQL', 'Tailwind CSS'],
    },
    {
      id: 15,
      slug: 'hexabitz-code-editor',
      title: 'Hexabitz Code Editor',
      titleAr: 'محرر كود هيكسابيتز',
      category: 'web',
      image: '/images/projects/ide.hexabitz.png',
      url: 'https://ide.hexabitz.com',
      date: '2022-12',
      tags: ['React', 'IDE', 'Monaco Editor'],
      featured: true,
      description: 'Online code editor for IoT hardware modules using Monaco Editor and React.',
      descriptionAr: 'محرر أكواد عبر الإنترنت لوحدات أجهزة IoT باستخدام Monaco Editor وReact.',
      longDescription: 'A web-based integrated development environment (IDE) for programming Hexabitz modular IoT hardware. Built with React and Monaco Editor, the IDE provides syntax highlighting, auto-completion, code compilation, and direct hardware flashing capabilities through a browser interface.',
      longDescriptionAr: 'بيئة تطوير متكاملة (IDE) عبر الويب لبرمجة أجهزة Hexabitz المعيارية لإنترنت الأشياء. مبنية بـ React وMonaco Editor.',
      role: 'Frontend Developer',
      roleAr: 'مطوّر واجهة أمامية',
      features: ['Monaco Editor integration with custom language support', 'Code compilation and hardware flashing via browser', 'Project management and file system', 'Syntax highlighting and auto-completion'],
      featuresAr: ['دمج Monaco Editor مع دعم لغة مخصصة', 'ترجمة الكود وبرمجة (Flash) الأجهزة عبر المتصفح', 'إدارة المشاريع ونظام الملفات', 'تمييز الصياغة والإكمال التلقائي'],
      stack: ['React', 'TypeScript', 'Monaco Editor', 'Node.js'],
    },
    {
      id: 16,
      slug: 'fastcaisse-pos-system',
      title: 'FastCaisse POS System',
      titleAr: 'نظام نقطة بيع FastCaisse',
      category: 'saas',
      image: '/images/projects/fastcaisse.jpg',
      url: 'https://fastcaisse.be/FastCaisse/',
      date: '2022-11',
      tags: ['Laravel', 'Vue', 'POS', 'SaaS'],
      description: 'Full-featured cloud POS system for restaurants with order management and reporting.',
      descriptionAr: 'نظام نقطة بيع سحابي كامل الميزات للمطاعم مع إدارة الطلبات والتقارير.',
      longDescription: 'The core FastCaisse point-of-sale system — a cloud-based POS designed for restaurant operations. Features include order management, table management, kitchen display system integration, receipt printing, payment processing, inventory tracking, and comprehensive reporting dashboards.',
      longDescriptionAr: 'نظام نقطة البيع الأساسي لـ FastCaisse — نظام POS سحابي مصمم لعمليات المطعم.',
      role: 'Co-Founder & Lead Developer',
      roleAr: 'مؤسس مشارك ومطوّر رئيسي',
      features: ['Real-time order and table management', 'Kitchen display system (KDS) integration', 'Multiple payment method support', 'Inventory tracking and alerts', 'Comprehensive sales reporting'],
      featuresAr: ['إدارة الطلبات والطاولات في الوقت الفعلي', 'دمج نظام عرض المطبخ (KDS)', 'دعم طرق دفع متعددة', 'تتبع المخزون والتنبيهات', 'تقارير مبيعات شاملة'],
      stack: ['Laravel', 'Vue.js', 'MySQL', 'Redis', 'PHP'],
    },
    {
      id: 17,
      slug: 'hexabitz-ide-system',
      title: 'Hexabitz IDE System',
      titleAr: 'نظام IDE هيكسابيتز',
      category: 'web',
      image: '/images/projects/ide.hexabitz.com.png',
      url: 'https://ide.hexabitz.com',
      date: '2022-10',
      tags: ['React', 'TypeScript', 'IoT'],
      description: 'Full IDE system for Hexabitz IoT platform with hardware integration.',
      descriptionAr: 'نظام IDE كامل لمنصة Hexabitz IoT مع تكامل الأجهزة.',
      role: 'Frontend Developer',
      roleAr: 'مطوّر واجهة أمامية',
      stack: ['React', 'TypeScript', 'Node.js'],
    },
    {
      id: 18,
      slug: 'hexabitz',
      title: 'Hexabitz',
      titleAr: 'هيكسابيتز',
      category: 'web',
      image: '/images/projects/hexabitz.png',
      url: 'https://hexabitz.com',
      date: '2022-09',
      tags: ['React', 'IoT', 'Hardware'],
      description: 'Main website for the Hexabitz modular IoT hardware platform.',
      descriptionAr: 'الموقع الرئيسي لمنصة Hexabitz المعيارية لأجهزة إنترنت الأشياء.',
      longDescription: 'The main website for Hexabitz — a modular electronics platform for building IoT prototypes. The site features product catalogs, documentation, tutorials, and community resources for hardware developers and makers.',
      longDescriptionAr: 'الموقع الرئيسي لـ Hexabitz — منصة إلكترونيات معيارية لبناء نماذج IoT الأولية.',
      role: 'Frontend Developer',
      roleAr: 'مطوّر واجهة أمامية',
      stack: ['React', 'JavaScript', 'HTML5', 'CSS3'],
    },
    {
      id: 19,
      slug: 'caresine-products',
      title: 'CareSine Products',
      titleAr: 'منتجات كيرسين',
      category: 'ecommerce',
      image: '/images/projects/caresine.jpg',
      url: 'https://caresine.com/caresine_new/',
      date: '2022-08',
      tags: ['PrestaShop', 'SEO', 'E-commerce'],
      featured: true,
      description: 'E-commerce platform for CareSine products with SEO-driven growth strategy.',
      descriptionAr: 'منصة تجارة إلكترونية لمنتجات كيرسين مع استراتيجية نمو مدفوعة بـ SEO.',
      longDescription: 'An e-commerce platform built on PrestaShop for CareSine, featuring product catalog management, shopping cart, secure checkout, and SEO optimization. Implemented structured data, optimized product pages, and improved site speed to drive organic traffic.',
      longDescriptionAr: 'منصة تجارة إلكترونية مبنية على PrestaShop لكيرسين، تتميز بإدارة كتالوج المنتجات وسلة التسوق والدفع الآمن وتحسين محركات البحث.',
      role: 'E-commerce Developer & SEO Specialist',
      roleAr: 'مطوّر تجارة إلكترونية ومتخصص SEO',
      features: ['Product catalog with advanced filtering', 'Secure checkout with multiple payment options', 'SEO-optimized product pages with structured data', 'Performance optimization for Core Web Vitals'],
      featuresAr: ['كتالوج منتجات مع تصفية متقدمة', 'دفع آمن مع خيارات دفع متعددة', 'صفحات منتجات محسّنة لمحركات البحث', 'تحسين الأداء لمؤشرات الويب الأساسية'],
      stack: ['PrestaShop', 'PHP', 'MySQL', 'JavaScript', 'SEO'],
    },
    {
      id: 20,
      slug: 'opinion-mining-system',
      title: 'Opinion Mining System',
      titleAr: 'نظام استخراج الآراء',
      category: 'web',
      image: '/images/projects/opinion mining.png',
      url: 'https://www.youtube.com/watch?v=NblAMGP0mFE',
      date: '2021-02',
      tags: ['Python', 'Django', 'NLP', 'ML'],
      description: 'NLP-based sentiment analysis system using machine learning for opinion mining.',
      descriptionAr: 'نظام تحليل مشاعر قائم على NLP باستخدام التعلم الآلي لاستخراج الآراء.',
      longDescription: 'A sentiment analysis and opinion mining system built with Python and Django. Uses NLP techniques and machine learning models to analyze and classify opinions from text data.',
      longDescriptionAr: 'نظام تحليل مشاعر واستخراج آراء مبني بـ Python وDjango. يستخدم تقنيات معالجة اللغة الطبيعية ونماذج التعلم الآلي.',
      role: 'ML Developer',
      roleAr: 'مطوّر تعلم آلي',
      features: ['Text sentiment classification', 'Data visualization dashboards', 'Batch text analysis', 'Exportable analysis reports'],
      featuresAr: ['تصنيف مشاعر النصوص', 'لوحات تصور البيانات', 'تحليل النصوص على دفعات', 'تقارير تحليل قابلة للتصدير'],
      stack: ['Python', 'Django', 'NLTK', 'scikit-learn', 'PostgreSQL'],
    },
    {
      id: 23,
      slug: 'opinion-mining-youtube',
      title: 'Opinion Mining in Social Media – YouTube',
      titleAr: 'استخراج الآراء من وسائل التواصل الاجتماعي – يوتيوب',
      category: 'ai',
      image: '/images/projects/opinion mining1.png',
      images: ['/images/projects/opinion mining1.png', '/images/projects/opinion mining3.png'],
      url: 'https://www.youtube.com/watch?v=z0T01nyIbXI',
      date: '2021-01',
      tags: ['Python', 'Django', 'Sentiment Analysis', 'Machine Learning', 'NLP', 'Data Science'],
      featured: false,
      description: 'Sentiment analysis system that mines and classifies opinions from YouTube social media comments using NLP and machine learning techniques.',
      descriptionAr: 'نظام تحليل مشاعر يستخرج ويصنّف الآراء من تعليقات يوتيوب باستخدام معالجة اللغة الطبيعية وتقنيات التعلم الآلي.',
      longDescription: 'An advanced sentiment analysis platform that collects and analyzes YouTube comments using natural language processing and machine learning. The system scrapes comments via the YouTube API, preprocesses text data, applies trained ML classifiers, and visualizes sentiment distributions.',
      longDescriptionAr: 'منصة تحليل مشاعر متقدمة تجمع تعليقات يوتيوب وتحللها باستخدام معالجة اللغة الطبيعية والتعلم الآلي.',
      role: 'ML Developer & Researcher',
      roleAr: 'مطوّر تعلم آلي وباحث',
      features: ['YouTube comment scraping via API', 'NLP text preprocessing pipeline', 'Multiple ML classifier comparison', 'Interactive sentiment distribution charts'],
      featuresAr: ['جمع تعليقات يوتيوب عبر API', 'مسار معالجة النصوص (NLP Pipeline)', 'مقارنة مصنفات ML متعددة', 'رسوم بيانية تفاعلية لتوزيع المشاعر'],
      stack: ['Python', 'Django', 'YouTube API', 'NLTK', 'scikit-learn', 'Matplotlib'],
    },
    {
      id: 21,
      slug: 'ecommerce-jackets',
      title: 'E-commerce Jackets',
      titleAr: 'متجر الجاكيتات',
      category: 'ecommerce',
      image: '/images/projects/ecommerce_jackets.webp',
      url: 'https://github.com/Azz3m90/ecommerce_jackets.git',
      github: 'https://github.com/Azz3m90/ecommerce_jackets.git',
      date: '2019-08',
      tags: ['Laravel', 'E-commerce', 'Bootstrap'],
      description: 'E-commerce platform for jacket sales built with Laravel and Bootstrap.',
      descriptionAr: 'منصة تجارة إلكترونية لبيع الجاكيتات مبنية بـ Laravel وBootstrap.',
      longDescription: 'A full-featured e-commerce web application for selling jackets, built with Laravel. Includes user authentication, product management, shopping cart, order processing, and admin panel.',
      longDescriptionAr: 'تطبيق ويب تجارة إلكترونية كامل الميزات لبيع الجاكيتات، مبني بـ Laravel.',
      role: 'Full Stack Developer',
      roleAr: 'مطوّر متكامل',
      stack: ['Laravel', 'PHP', 'MySQL', 'Bootstrap', 'JavaScript'],
    },
    {
      id: 22,
      slug: 'university-indexer',
      title: 'University Indexer',
      titleAr: 'فهرس الجامعة',
      category: 'web',
      image: '/images/projects/universityindexer.png',
      url: 'https://azz3m90.github.io/Project/',
      github: 'https://azz3m90.github.io/Project/',
      date: '2019-06',
      tags: ['JavaScript', 'HTML5', 'CSS3'],
      description: 'University course indexing and search tool built with vanilla JavaScript.',
      descriptionAr: 'أداة لفهرسة مقررات الجامعة والبحث فيها، مبنية بـ JavaScript.',
      longDescription: 'A client-side university course indexing application built with pure JavaScript, HTML5, and CSS3. Allows students to search and filter university courses, view schedules, and plan their semester.',
      longDescriptionAr: 'تطبيق فهرسة مقررات جامعية من جانب العميل مبني بـ JavaScript وHTML5 وCSS3.',
      role: 'Frontend Developer',
      roleAr: 'مطوّر واجهة أمامية',
      stack: ['JavaScript', 'HTML5', 'CSS3'],
    },
  ]

  const featuredProjects = computed(() => projects.filter(p => p.featured))

  const filterProjects = (category: string) => {
    if (category === 'all') return projects
    return projects.filter(p => p.category === category)
  }

  const getProjectBySlug = (slug: string): Project | undefined => {
    return projects.find(p => p.slug === slug)
  }

  return { projects, featuredProjects, filterProjects, getProjectBySlug }
}
