export interface Project {
  id: number
  title: string
  titleAr: string
  category: 'saas' | 'ecommerce' | 'web' | 'design'
  image: string
  url: string
  github?: string
  date: string
  dateLabel: string
  tags: string[]
  featured?: boolean
  description?: string
  descriptionAr?: string
}

export const useProjects = () => {
  const projects: Project[] = [
    {
      id: 1,
      title: 'FastCaisse Ordering Platform',
      titleAr: 'منصة طلب FastCaisse',
      category: 'saas',
      image: '/images/projects/ordering-platform.png',
      url: 'https://fastcaisse-ordering-platform.vercel.app/en/',
      date: '2026-01',
      dateLabel: 'January 2026',
      tags: ['Vue 3', 'Laravel', 'SaaS', 'Multi-language'],
      featured: true,
      description: 'Multi-restaurant online ordering SaaS with kiosk mode, payment integration, and multi-language support.',
      descriptionAr: 'منصة طلب طعام SaaS متعددة المطاعم مع وضع الكشك ودمج الدفع ودعم متعدد اللغات.',
    },
    {
      id: 2,
      title: 'FastCaisse Kiosk',
      titleAr: 'كشك FastCaisse',
      category: 'saas',
      image: '/images/projects/kiosk.png',
      url: 'https://kiosk.fastfoodelivery.be/',
      date: '2025-12',
      dateLabel: 'December 2025',
      tags: ['Vue 3', 'Kiosk', 'Touch UI'],
      featured: true,
    },
    {
      id: 3,
      title: 'Lindenberg Apotheke',
      titleAr: 'صيدلية ليندنبرغ',
      category: 'web',
      image: '/images/projects/Lindenberg-Apotheke.png',
      url: 'https://lindenberg-apotheke.de/',
      date: '2025-11',
      dateLabel: 'November 2025',
      tags: ['Laravel', 'SEO', 'Germany'],
    },
    {
      id: 4,
      title: 'Astramind',
      titleAr: 'أسترامايند',
      category: 'web',
      image: '/images/projects/Astramind.png',
      url: 'https://astramind.de/',
      date: '2025-09',
      dateLabel: 'September 2025',
      tags: ['React', 'SEO', 'Germany'],
    },
    {
      id: 5,
      title: 'Emtethal Landing Page',
      titleAr: 'صفحة امتثال',
      category: 'web',
      image: '/images/projects/EmtethalLandpage.png',
      url: 'https://emtethal.com/',
      date: '2025-09',
      dateLabel: 'September 2025',
      tags: ['Laravel', 'Arabic', 'Landing Page'],
    },
    {
      id: 6,
      title: 'FastCaisse Marketing Site',
      titleAr: 'موقع FastCaisse التسويقي',
      category: 'saas',
      image: '/images/projects/FastCaisse-langing.png',
      url: 'https://FastCaisse.de/',
      date: '2025-06',
      dateLabel: 'June 2025',
      tags: ['Nuxt', 'SEO', 'Marketing'],
      featured: true,
    },
    {
      id: 7,
      title: 'Little Lemon Booking – Figma',
      titleAr: 'حجز ليتل ليمون',
      category: 'design',
      image: '/images/projects/littlelemonbookTable.png',
      url: 'https://www.figma.com/design/MXOErAiiJyuwJGhO9HCHuM/',
      date: '2024-10',
      dateLabel: 'October 2024',
      tags: ['Figma', 'UX/UI', 'Coursera'],
    },
    {
      id: 8,
      title: 'IL Moro Group',
      titleAr: 'مجموعة إيل مورو',
      category: 'web',
      image: '/images/projects/www.ilmorogroup.be.png',
      url: 'https://www.ilmorogroup.be/',
      date: '2024-09',
      dateLabel: 'September 2024',
      tags: ['Laravel', 'Belgium', 'Restaurant'],
    },
    {
      id: 9,
      title: 'FastCaisse Online Ordering',
      titleAr: 'طلب FastCaisse الإلكتروني',
      category: 'saas',
      image: '/images/projects/fastcaisse_Food_PortalOrdering.png',
      url: 'https://fastcaisse.be/food/public/start',
      date: '2024-06',
      dateLabel: 'June 2024',
      tags: ['Laravel', 'Vue', 'Food Delivery'],
    },
    {
      id: 10,
      title: 'Gelato Naturale',
      titleAr: 'جيلاتو ناتورالي',
      category: 'web',
      image: '/images/projects/gelatonaturale.jpg',
      url: 'https://gelatonaturale.be/gelatonaturale/',
      date: '2024-03',
      dateLabel: 'March 2024',
      tags: ['Laravel', 'Belgium', 'Ice Cream'],
    },
    {
      id: 11,
      title: 'Seetaha Award Debugger',
      titleAr: 'مُصحح سيتاها',
      category: 'web',
      image: '/images/projects/seetahaward.jpg',
      url: '#',
      date: '2024-01',
      dateLabel: 'January 2024',
      tags: ['PHP', 'Debug', 'WordPress'],
    },
    {
      id: 12,
      title: 'Seetah SCC',
      titleAr: 'سيتاه SCC',
      category: 'web',
      image: '/images/projects/seetahscc.jpg',
      url: 'https://seetahscc.org/ar/',
      date: '2024-01',
      dateLabel: 'January 2024',
      tags: ['Arabic', 'RTL', 'WordPress'],
    },
    {
      id: 13,
      title: 'Matthias and Sea – Seafood',
      titleAr: 'ماتياس والبحر',
      category: 'web',
      image: '/images/projects/matthiasandsea.png',
      url: 'https://www.matthiasandsea.be/matthias-and-sea/',
      date: '2023-12',
      dateLabel: 'December 2023',
      tags: ['PHP', 'Restaurant', 'Belgium'],
    },
    {
      id: 14,
      title: 'Geco Consulting',
      titleAr: 'جيكو للاستشارات',
      category: 'web',
      image: '/images/projects/gecocar.jpg',
      url: 'https://gecoconsulting.be',
      date: '2023-11',
      dateLabel: 'November 2023',
      tags: ['Laravel', 'Belgium', 'Consulting'],
    },
    {
      id: 15,
      title: 'Hexabitz Code Editor',
      titleAr: 'محرر كود هيكسابيتز',
      category: 'web',
      image: '/images/projects/ide.hexabitz.png',
      url: 'https://ide.hexabitz.com',
      date: '2022-12',
      dateLabel: 'December 2022',
      tags: ['React', 'IDE', 'Monaco Editor'],
      featured: true,
    },
    {
      id: 16,
      title: 'FastCaisse POS System',
      titleAr: 'نظام نقطة بيع FastCaisse',
      category: 'saas',
      image: '/images/projects/fastcaisse.jpg',
      url: 'https://fastcaisse.be/FastCaisse/',
      date: '2022-11',
      dateLabel: 'November 2022',
      tags: ['Laravel', 'Vue', 'POS', 'SaaS'],
    },
    {
      id: 17,
      title: 'Hexabitz IDE System',
      titleAr: 'نظام IDE هيكسابيتز',
      category: 'web',
      image: '/images/projects/ide.hexabitz.com.png',
      url: 'https://ide.hexabitz.com',
      date: '2022-10',
      dateLabel: 'October 2022',
      tags: ['React', 'TypeScript', 'IoT'],
    },
    {
      id: 18,
      title: 'Hexabitz',
      titleAr: 'هيكسابيتز',
      category: 'web',
      image: '/images/projects/hexabitz.png',
      url: 'https://hexabitz.com',
      date: '2022-09',
      dateLabel: 'September 2022',
      tags: ['React', 'IoT', 'Hardware'],
    },
    {
      id: 19,
      title: 'CareSine Products',
      titleAr: 'منتجات كيرسين',
      category: 'ecommerce',
      image: '/images/projects/caresine.jpg',
      url: 'https://caresine.com/caresine_new/',
      date: '2022-08',
      dateLabel: 'August 2022',
      tags: ['PrestaShop', 'SEO', 'E-commerce'],
      featured: true,
    },
    {
      id: 20,
      title: 'Opinion Mining System',
      titleAr: 'نظام استخراج الآراء',
      category: 'web',
      image: '/images/projects/opinion mining.png',
      url: 'https://www.youtube.com/watch?v=NblAMGP0mFE',
      date: '2021-02',
      dateLabel: 'February 2021',
      tags: ['Python', 'Django', 'NLP', 'ML'],
    },
    {
      id: 21,
      title: 'E-commerce Jackets',
      titleAr: 'متجر الجاكيت',
      category: 'ecommerce',
      image: '/images/projects/ecommerce_jackets.webp',
      url: 'https://github.com/Azz3m90/ecommerce_jackets.git',
      github: 'https://github.com/Azz3m90/ecommerce_jackets.git',
      date: '2019-08',
      dateLabel: 'August 2019',
      tags: ['Laravel', 'E-commerce', 'Bootstrap'],
    },
    {
      id: 22,
      title: 'University Indexer',
      titleAr: 'فهرس الجامعة',
      category: 'web',
      image: '/images/projects/universityindexer.png',
      url: 'https://azz3m90.github.io/Project/',
      github: 'https://azz3m90.github.io/Project/',
      date: '2019-06',
      dateLabel: 'June 2019',
      tags: ['JavaScript', 'HTML5', 'CSS3'],
    },
  ]

  const featuredProjects = computed(() => projects.filter(p => p.featured))

  const filterProjects = (category: string) => {
    if (category === 'all') return projects
    return projects.filter(p => p.category === category)
  }

  return { projects, featuredProjects, filterProjects }
}
